- hosts: ubuntu
  become: true
  tasks:
    - name: Ensure Apache and UFW are installed
      apt:
        name:
          - apache2
          - ufw
        state: present
        update_cache: yes
    - name: Ensure UFW allows HTTP
      ufw:
        rule: allow
        port: '80'
    - name: Ensure UFW allows HTTPS
      ufw:
        rule: allow
        port: '443'
    - name: Enable UFW
      ufw:
        state: enabled
    - name: Ensure MySQL backup directory exists
      file:
        path: /var/backups/mysql
        state: directory
        owner: root
        group: root
        mode: '0700'
    - name: Schedule daily MySQL dump at 03:00
      cron:
        name: "daily mysql backup"
        minute: "0"
        hour: "3"
        job: "mysqldump --single-transaction --routines --events --all-databases | gzip > /var/backups/mysql/backup-$(date +\\%F).sql.gz"
        user: root
    - name: Remove MySQL backups older than 14 days
      cron:
        name: "cleanup old mysql backups"
        minute: "0"
        hour: "4"
        job: "find /var/backups/mysql -type f -mtime +14 -name '*.gz' -delete"
        user: root
    - name: Ensure snapshot script directory exists
      file:
        path: /usr/local/bin
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Deploy IONOS snapshot script
      copy:
        dest: /usr/local/bin/ionos-snapshot.sh
        content: |
          #!/usr/bin/env bash
          export IONOS_TOKEN="{{ ionos_token }}"
          SERVER_ID="{{ server_id }}"
          VOLUME_ID="{{ volume_id }}"
          curl -s -X POST \\
            "https://api.ionos.com/cloudapi/v5/servers/\${SERVER_ID}/volumes/\${VOLUME_ID}/create-snapshot" \\
            -H "Authorization: Bearer \${IONOS_TOKEN}" \\
            -H "Content-Type: application/json" \\
            -d '{"name":"snapshot-'"$(date +%F)"'"}'
        owner: root
        group: root
        mode: '0755'

    - name: Schedule daily IONOS snapshot at 01:00
      cron:
        name: "daily ionos snapshot"
        minute: "0"
        hour: "1"
        job: "/usr/local/bin/ionos-snapshot.sh"
        user: root
